### ISSUE TITLE
Meal plan sensor not working

### ISSUE THREAD

**Issue by stefdewilde** [custom-components/grocy#124]
## Unless all relevant information is provided, I can't help you

**Describe the bug**

The meal_plan sensor doesn't update/work and it gives this error: 

Update of Meal_plan failed with 'NoneType' object has no attribute 'name'

**Expected behavior**
It should normally work, right?

**To Reproduce**
Happens all the time. Restarting, updating, reinstall,..

**What is your installed versions of Home Assistant, Grocy and this integration?**
HA 2021.4.3
integration 3.0.1
Grocy addon: 0.12.0

**How do you have Grocy installed? Add-on or external?**
addon

**Have you added debugging to the log, and what does the log say?**
Update of Meal_plan failed with 'NoneType' object has no attribute 'name'

2021-04-11 12:23:35 ERROR (MainThread) [custom_components.grocy] Update of Meal_plan failed with 'NoneType' object has no attribute 'name'

**Comment by isabellaalstrom** [comment]
Do you have any meal plans added in Grocy?

**Comment by stefdewilde** [comment]
https://i.imgur.com/V3OCjRV.png

Yes, I have added several recipes and also in the meal plan

**Comment by isabellaalstrom** [comment]
Should be fixed with latest release. Please verify.

**Comment by stefdewilde** [comment]
Hello

I still get same error:

Logger: custom_components.grocy
Source: custom_components/grocy/__init__.py:104
Integration: Grocy (documentation)
First occurred: 1:11:12 PM (1 occurrences)
Last logged: 1:11:12 PM

Update of Meal_plan failed with 'NoneType' object has no attribute 'name'

**Comment by isabellaalstrom** [comment]
Alright. Basically these types of errors happens when the integration is expecting something that doesn't exist in the setup. I will try to find out what's wrong, but I can't promise it will be soon.

**Comment by isabellaalstrom** [comment]
It could be something with recipes maybe, or the ingredients.
You could try to only add one recipe to the meal plan and see if the error still persists. If not, add one by one until you see which recipe makes the error re-appear. If it exists with only one (or none) recipe, try another one.

**Comment by isabellaalstrom** [comment]
Also, what features do you have enabled in Grocy? Do you have recipe and stock?

**Comment by stefdewilde** [comment]
Hello,

I only have recipes, stock and calander enabled (together with meal plan).
I still have to check the recipe issue

**Comment by stefdewilde** [comment]
Hello
I decided to delete all the recipes with a ( ) in it and it seems to work..
thanks!

**Comment by isabellaalstrom** [comment]
Alright, seems like it can't handle special characters then maybe. I'll close this issue again then :)
